micronaut:
  application:
    name: deckerdent
  security:
    #authentication: bearer
    #token:
    #jwt:
    #signatures:
    #secret:
    #generator:
    #secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
    intercept-url-map:
      - access: isAnonymous()
        pattern: /graphql/**
      - access: isAnonymous()
        pattern: /graphiql/**
  router:
    static-resources:
datasources:
  default:
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
database:
  max: 50
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql
